// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LogoSvg from "./logo.svg";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as Park$RescriptReactIntro from "./Park.bs.js";
import * as NavBar$RescriptReactIntro from "./NavBar.bs.js";
import * as Subtitle$RescriptReactIntro from "./Subtitle.bs.js";
import * as LandingPage$RescriptReactIntro from "./LandingPage.bs.js";

import './App.css';
;

var logo = LogoSvg;

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component;
  var exit = 0;
  if (match) {
    if (match.hd === "park") {
      var match$1 = match.tl;
      if (match$1 && !match$1.tl) {
        var name = match$1.hd;
        var fullName = Caml_array.get(name.replace(/%20/, " ").split("%20"), 0) + " National Park";
        component = React.createElement("div", undefined, React.createElement(Subtitle$RescriptReactIntro.make, {
                  name: fullName
                }), React.createElement(Park$RescriptReactIntro.make, {
                  name: name
                }));
      } else {
        exit = 1;
      }
    } else {
      exit = 1;
    }
  } else {
    component = React.createElement("div", undefined, React.createElement(Subtitle$RescriptReactIntro.make, {
              name: "Select a National Park Below!"
            }), React.createElement(LandingPage$RescriptReactIntro.make, {}));
  }
  if (exit === 1) {
    component = React.createElement("div", undefined, "Route not found");
  }
  return React.createElement("div", undefined, React.createElement(NavBar$RescriptReactIntro.make, {}), component);
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
