// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DayChart$RescriptReactIntro from "./DayChart.bs.js";
import * as HourChart$RescriptReactIntro from "./HourChart.bs.js";
import * as MonthChart$RescriptReactIntro from "./MonthChart.bs.js";

function Charts(Props) {
  var title = Props.title;
  var hour_data = Props.hour_data;
  var day_data = Props.day_data;
  var month_data = Props.month_data;
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "center"
                }, title), React.createElement("br", undefined), React.createElement(HourChart$RescriptReactIntro.make, {
                  data: hour_data
                }), React.createElement("br", undefined), React.createElement(DayChart$RescriptReactIntro.make, {
                  data: day_data
                }), React.createElement("br", undefined), React.createElement(MonthChart$RescriptReactIntro.make, {
                  data: month_data
                }), React.createElement("br", undefined));
}

var make = Charts;

export {
  make ,
  
}
/* react Not a pure module */
