// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Recharts from "recharts";
import * as XAxis$Recharts from "@float-capital/rescript-recharts/src/XAxis.bs.js";
import * as YAxis$Recharts from "@float-capital/rescript-recharts/src/YAxis.bs.js";
import * as Tooltip$Recharts from "@float-capital/rescript-recharts/src/Tooltip.bs.js";
import * as BarChart$Recharts from "@float-capital/rescript-recharts/src/BarChart.bs.js";
import * as Chart$RescriptReactIntro from "./Chart.bs.js";
import * as ResponsiveContainer$Recharts from "@float-capital/rescript-recharts/src/ResponsiveContainer.bs.js";

function HourChart(Props) {
  var data = Props.data;
  return React.createElement(Chart$RescriptReactIntro.make, {
              title: "Activity by Hour",
              children: React.createElement(Recharts.ResponsiveContainer, Curry._3(ResponsiveContainer$Recharts.makeProps({
                              TAG: /* Px */0,
                              _0: 400
                            }, {
                              TAG: /* Px */0,
                              _0: 900
                            })(undefined, undefined, undefined, undefined, undefined), React.createElement(Recharts.BarChart, Curry.app(BarChart$Recharts.makeProps({
                                      TAG: /* Px */0,
                                      _0: 1
                                    }, undefined)(data), [
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                {
                                  top: 5,
                                  right: 30,
                                  bottom: 5,
                                  left: 20
                                },
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                undefined,
                                null,
                                undefined,
                                undefined
                              ]), React.createElement(Recharts.CartesianGrid, {
                                strokeDasharray: "3 3"
                              }), React.createElement(Recharts.XAxis, Curry.app(XAxis$Recharts.makeProps(undefined)(undefined, undefined, undefined, undefined, undefined, undefined, "hour", undefined, undefined, undefined), [
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined
                                  ])), React.createElement(Recharts.YAxis, Curry.app(YAxis$Recharts.makeProps(undefined)(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined
                                  ])), React.createElement(Recharts.Bar, {
                                dataKey: "gen_count",
                                fill: "#71ECFF",
                                name: "Any Given Day",
                                stackId: "a"
                              }), React.createElement(Recharts.Bar, {
                                dataKey: "weekday_count",
                                fill: "#71FF89",
                                name: "Weekdays",
                                stackId: "b"
                              }), React.createElement(Recharts.Bar, {
                                dataKey: "weekend_count",
                                fill: "#FF71E1",
                                name: "Weekends",
                                stackId: "c"
                              }), React.createElement(Recharts.Tooltip, Curry.app(Tooltip$Recharts.makeProps(undefined)(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined,
                                    undefined
                                  ])), React.createElement(Recharts.Legend, {
                                align: "center",
                                iconType: "square"
                              })), undefined, undefined))
            });
}

var make = HourChart;

export {
  make ,
  
}
/* react Not a pure module */
