// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function LandingPage$ParkButton(Props) {
  var name = Props.name;
  var linkTo = "/park/" + name + " National Park";
  return React.createElement("div", {
              className: "park-button",
              onClick: (function (param) {
                  return RescriptReactRouter.push(linkTo);
                })
            }, name);
}

var ParkButton = {
  make: LandingPage$ParkButton
};

function LandingPage(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "row"
                }, React.createElement(LandingPage$ParkButton, {
                      name: "Acadia"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Shenandoah"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Joshua Tree"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Grand Teton"
                    })), React.createElement("div", {
                  className: "row"
                }, React.createElement(LandingPage$ParkButton, {
                      name: "Death Valley"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Mount Rainier"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Yellowstone"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Zion"
                    })), React.createElement("div", {
                  className: "row"
                }, React.createElement(LandingPage$ParkButton, {
                      name: "Yosemite"
                    }), React.createElement(LandingPage$ParkButton, {
                      name: "Glacier"
                    })));
}

var make = LandingPage;

export {
  ParkButton ,
  make ,
  
}
/* react Not a pure module */
