// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function NavBar$NavButton(Props) {
  var name = Props.name;
  var selected = Props.selected;
  var linkTo = Props.linkTo;
  var style = selected === name ? ({
        backgroundColor: "#efefef",
        padding: "1ex"
      }) : ({
        backgroundColor: "#39D99F",
        padding: "1ex"
      });
  return React.createElement("div", {
              style: style,
              onClick: (function (param) {
                  return RescriptReactRouter.push(linkTo);
                })
            }, name);
}

var NavButton = {
  make: NavBar$NavButton
};

function NavBar$Title(Props) {
  var style = {
    backgroundColor: "#DEFFF3",
    padding: "1ex"
  };
  return React.createElement("div", {
              style: style
            }, "National Park Activity Tracker");
}

var Title = {
  make: NavBar$Title
};

function NavBar(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var selected = match && match.hd === "park" ? "Park Activity Tracker" : "Home";
  return React.createElement("div", {
              className: "nav-bar"
            }, React.createElement("div", {
                  className: "nav-button"
                }, React.createElement(NavBar$NavButton, {
                      name: "Home",
                      selected: selected,
                      linkTo: "/"
                    })), React.createElement("div", {
                  className: "title"
                }, React.createElement(NavBar$Title, {})));
}

var make = NavBar;

export {
  NavButton ,
  Title ,
  make ,
  
}
/* react Not a pure module */
