// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Charts$RescriptReactIntro from "./Charts.bs.js";

import './styles/main.css'
;

function Park(Props) {
  var name = Props.name;
  var match = React.useState(function () {
        
      });
  var setData = match[1];
  var data = match[0];
  console.log(name);
  React.useEffect((function () {
          var request = new XMLHttpRequest();
          request.addEventListener("load", (function (param) {
                  var response = JSON.parse(request.response);
                  console.log(response);
                  return Curry._1(setData, (function (param) {
                                return response;
                              }));
                }));
          request.open("GET", "http://localhost:9000/park?name=" + name);
          request.send();
          
        }), []);
  if (data !== undefined) {
    return React.createElement("div", {
                className: "row"
              }, React.createElement(Charts$RescriptReactIntro.make, {
                    title: "Interest in Park: Tweets Made About Park",
                    hour_data: data.counts.hour,
                    day_data: data.counts.day,
                    month_data: data.counts.month
                  }), React.createElement(Charts$RescriptReactIntro.make, {
                    title: "Activity in Park: Tweets Made In Park",
                    hour_data: data.tweets.hour,
                    day_data: data.tweets.day,
                    month_data: data.tweets.month
                  }));
  } else {
    return React.createElement("div", undefined, "Unable to fetch data!");
  }
}

var make = Park;

export {
  make ,
  
}
/*  Not a pure module */
