// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Subtitle(Props) {
  var name = Props.name;
  return React.createElement("div", {
              className: "center"
            }, React.createElement("h1", undefined, name));
}

var make = Subtitle;

export {
  make ,
  
}
/* react Not a pure module */
